#!/bin/sh

iptables -A INPUT -p udp --dport 53 -m hashlimit --hashlimit-upto 20/sec --hashlimit-burst 20 --hashlimit-mode srcip --hashlimit-name packet_rate_limit -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j DROP

sleep infinity
