#!/bin/sh

var2list(){
        local PREFIX=$1
        seq 1 9 |
        while read n; do
                [[ -n $(eval echo -n \$$PREFIX$n) ]] && eval echo $(eval echo \$$PREFIX$n);
        done
}

iptables -N UPSTREAM
var2list GLOBAL_DNS | xargs -I {} iptables -A INPUT -s {} -j UPSTREAM
iptables -A UPSTREAM -p udp -m udp --sport 53 -m u32 --u32 "36=0" -j DROP
iptables -A UPSTREAM -p udp -m udp --sport 53 -m u32 --u32 "28&0x10=0" -j DROP
iptables -A UPSTREAM -p tcp -m tcp --sport 53 --tcp-flags RST RST -j DROP

sleep infinity
