#!/bin/bash

build_dnscrypt-wrapper(){
    apk add libevent libsodium 
    apk add -t build-deps build-base git autoconf libsodium-dev libevent-dev bsd-compat-headers
    export DNSCRYPT_WRAPPER_SRC=$SRC_DIR/dnscrypt-wrapper
    git clone --recursive --depth=1 --branch=v$DNSCRYPT_VERSION git://github.com/cofyc/dnscrypt-wrapper.git $DNSCRYPT_WRAPPER_SRC
    cd $DNSCRYPT_WRAPPER_SRC
    make configure
    ./configure
    make
    make install
}

get_china_list(){
    LIST_DIR=$SRC_DIR/dnsmasq-china-list
    git clone --depth=1 https://github.com/felixonmars/dnsmasq-china-list.git $LIST_DIR
    cd $LIST_DIR
    make raw
    install accelerated-domains.china.raw.txt /opt/
}

build_pdns_recursor(){
    apk add -t build-deps build-base boost-dev lua-dev libressl-dev curl
    apk add boost libgcc libressl2.5-libcrypto libstdc++ lua5.1-libs
    #apk add -t build-deps build-base boost-dev lua-dev libressl-dev git autoconf automake libtool pkgconf ragel curl
    export PDNS_RECURSOR_SRC=$SRC_DIR/pdns_recursor
    mkdir -p $PDNS_RECURSOR_SRC
    curl -sSL http://downloads.powerdns.com/releases/pdns-recursor-$PDNS_RECURSOR_VERSION.tar.bz2 | tar -C $PDNS_RECURSOR_SRC --strip-components=1 -xjf -
    cd $PDNS_RECURSOR_SRC
	./configure --prefix=/usr \
		--sysconfdir=/etc/pdns \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--libdir=/usr/lib/pdns \
		--disable-static
    make -j `getconf _NPROCESSORS_ONLN`
    make install
    rm /etc/pdns/recursor.conf-dist
    addgroup -S recursor 2>/dev/null
    adduser -S -D -H -h /var/empty -s /bin/false -G recursor -g recursor recursor 2>/dev/null
}

set -x
set -e

export SRC_DIR=/usr/local/src
mkdir -p $SRC_DIR

apk update
build_dnscrypt-wrapper
build_pdns_recursor
get_china_list
apk add \
    supervisor \
    iptables \
    ip6tables \
    collectd-bind \
    collectd-network \
    fail2ban
mkdir -p /var/log/named \
        /var/log/supervisor \
        /srv/dnscrypt-wrapper \
        /var/run/fail2ban
rm /etc/fail2ban/jail.d/alpine-ssh.conf
cd /
apk del --purge build-deps
rm -rf $SRC_DIR \
    /var/cache/apk/*
