#!/bin/bash

iptables -N UPSTREAM
iptables -A INPUT -s $GLOBAL_DNS1 -j UPSTREAM
iptables -A INPUT -s $GLOBAL_DNS2 -j UPSTREAM
iptables -A UPSTREAM -p udp -m udp --sport 53 -m u32 --u32 "36=0" -j DROP
iptables -A UPSTREAM -p udp -m udp --sport 53 -m u32 --u32 "28&0x10=0" -j DROP
iptables -A UPSTREAM -p tcp -m tcp --sport 53 --tcp-flags RST RST -j DROP


if [[ $CHINA_DNS2 ]]; then
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; $CHINA_DNS2; }; };|" /opt/accelerated-domains.china.raw.txt > /etc/bind/named.conf.china
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; $CHINA_DNS2; }; };|" /opt/apple.china.raw.txt > /etc/bind/named.conf.apple
else
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; }; };|" /opt/accelerated-domains.china.raw.txt > /etc/bind/named.conf.china
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; }; };|" /opt/apple.china.raw.txt > /etc/bind/named.conf.apple
fi

