#!/bin/bash

iptables -N UPSTREAM
iptables -A INPUT -s $GLOBAL_DNS1 -j UPSTREAM
iptables -A INPUT -s $GLOBAL_DNS2 -j UPSTREAM
iptables -A UPSTREAM -p udp -m udp --sport 53 -m u32 --u32 "36=0" -j DROP
iptables -A UPSTREAM -p tcp -m tcp --sport 53 --tcp-flags RST RST -j DROP


if [[ $CHINA_DNS2 ]]; then
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; $CHINA_DNS2; }; };|" /opt/accelerated-domains.china.raw.txt > /etc/bind/named.conf.china
else
    sed -e "s|\(.*\)|zone "\\1." {type forward; forwarders { $CHINA_DNS1; }; };|" /opt/accelerated-domains.china.raw.txt > /etc/bind/named.conf.china
fi


cd /srv/dnscrypt-wrapper
[[ -f secret.key  ]] || dnscrypt-wrapper --gen-provider-keypair
[[ -f public.key  ]] || >&2 echo "'public.key' does not exist. Please delete secret.key, and try again." 
[[ -f fingerprint ]] || dnscrypt-wrapper --show-provider-publickey-fingerprint --provider-publickey-file public.key > fingerprint
[[ -f server.key  ]] || dnscrypt-wrapper --gen-crypt-keypair --crypt-secretkey-file=server.key
[[ -f server.cert ]] || dnscrypt-wrapper --gen-cert-file --crypt-secretkey-file=server.key --provider-cert-file=server.cert \
    --provider-publickey-file=public.key --provider-secretkey-file=secret.key

chmod go-rwx server.key secret.key
